# Generated by Django 5.0.3 on 2024-03-07 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ficha_historica', models.TextField()),
                ('fecha_de_ingreso', models.DateField()),
                ('personal_ingresante', models.CharField(max_length=200)),
                ('fecha_de_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
