# Generated by Django 5.0.3 on 2024-03-08 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Piezas',
        ),
    ]
