# Generated by Django 5.0.3 on 2024-03-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_rename_articulo_piezas'),
    ]

    operations = [
        migrations.AddField(
            model_name='piezas',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='piezas/'),
        ),
    ]
