# Generated by Django 5.0.3 on 2024-03-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_piezas_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezas',
            name='imagen',
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='piezas/')),
                ('pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='articulo.piezas')),
            ],
        ),
    ]
