# Generated by Django 5.0.3 on 2024-03-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_remove_piezas_imagen_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_identidad', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numero_contacto', models.CharField(max_length=15)),
                ('correo_electronico', models.EmailField(max_length=100)),
                ('direccion_domicilio', models.TextField()),
            ],
        ),
    ]
