# Generated by Django 5.0.3 on 2024-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0009_alter_bitacora_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donante',
            old_name='numero_contacto',
            new_name='numero_telefono',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='correo_electronico',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='direccion_domicilio',
        ),
        migrations.RemoveField(
            model_name='donante',
            name='nombre',
        ),
        migrations.AddField(
            model_name='donante',
            name='nombre_apellido',
            field=models.CharField(default='Nombre Apellido', max_length=200),
        ),
        migrations.AlterField(
            model_name='donante',
            name='cedula_identidad',
            field=models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('P', 'RIF PERSONAL'), ('J', 'RIF JURIDICO')], max_length=10, unique=True),
        ),
    ]
