# Generated by Django 5.0.3 on 2024-04-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0010_rename_numero_contacto_donante_numero_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donante',
            name='nombre_apellido',
            field=models.CharField(max_length=200),
        ),
    ]
