# Generated by Django 5.0.3 on 2024-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0011_alter_donante_nombre_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donante',
            name='cedula_identidad',
        ),
        migrations.AddField(
            model_name='donante',
            name='numero_identidad',
            field=models.CharField(default='0000000000', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='donante',
            name='tipo_identidad',
            field=models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('P', 'RIF PERSONAL'), ('J', 'RIF JURIDICO')], default='V', max_length=1),
        ),
    ]
