# Generated by Django 5.0.3 on 2024-04-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0012_remove_donante_cedula_identidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artesano',
            fields=[
                ('codigo', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_y_apellido', models.CharField(max_length=200)),
                ('biografia', models.TextField()),
            ],
        ),
    ]
