# Generated by Django 5.0.3 on 2024-04-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0013_artesano'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosTecnicos',
            fields=[
                ('Codigo_de_Datos_Tecnicos', models.AutoField(primary_key=True, serialize=False)),
                ('Procedencia', models.CharField(max_length=200)),
                ('Cultura', models.CharField(max_length=200)),
                ('Valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Propetario_Original', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('Codigo_de_Estado_de_Conservacion', models.AutoField(primary_key=True, serialize=False)),
                ('Condicion', models.CharField(max_length=200)),
                ('Integridad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('Codigo_de_Referencia', models.AutoField(primary_key=True, serialize=False)),
                ('Exposiciones', models.CharField(max_length=200)),
                ('Tratamiento', models.CharField(max_length=200)),
                ('Ubicacion_Deposito', models.CharField(max_length=200)),
            ],
        ),
    ]
