# Generated by Django 5.0.3 on 2024-04-29 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0014_datostecnicos_estadoconservacion_referencias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_solicitante', models.CharField(max_length=100)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('pieza_solicitada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articulo.piezas')),
            ],
        ),
    ]
